"""Initial database

Revision ID: e77f12cb5801
Revises: 
Create Date: 2020-06-23 17:51:43.563476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f12cb5801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_all_spectra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mz', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_spectra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mz', sa.Float(), nullable=False),
    sa.Column('int_rel', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_spectra')
    op.drop_table('temp_all_spectra')
    # ### end Alembic commands ###
